// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAy1tdU9HVb3KpNTIOLMiVKXU5MChTecU8',
    appId: '1:328362817116:web:882917ae26bf4d54895899',
    messagingSenderId: '328362817116',
    projectId: 'bracu-cart',
    authDomain: 'bracu-cart.firebaseapp.com',
    storageBucket: 'bracu-cart.firebasestorage.app',
    measurementId: 'G-R337VC69G2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDzuhoWmNEO81i9a_u-z8kM120CiwR8rPs',
    appId: '1:328362817116:android:6e9a6ff93c8b3304895899',
    messagingSenderId: '328362817116',
    projectId: 'bracu-cart',
    storageBucket: 'bracu-cart.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCIMJ5AJGRYXlSKNvIThAfHH-g3KuPLPYM',
    appId: '1:328362817116:ios:06dc2e1108deae36895899',
    messagingSenderId: '328362817116',
    projectId: 'bracu-cart',
    storageBucket: 'bracu-cart.firebasestorage.app',
    iosBundleId: 'com.example.bracuCart',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCIMJ5AJGRYXlSKNvIThAfHH-g3KuPLPYM',
    appId: '1:328362817116:ios:06dc2e1108deae36895899',
    messagingSenderId: '328362817116',
    projectId: 'bracu-cart',
    storageBucket: 'bracu-cart.firebasestorage.app',
    iosBundleId: 'com.example.bracuCart',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAy1tdU9HVb3KpNTIOLMiVKXU5MChTecU8',
    appId: '1:328362817116:web:54a2692aa7ce650c895899',
    messagingSenderId: '328362817116',
    projectId: 'bracu-cart',
    authDomain: 'bracu-cart.firebaseapp.com',
    storageBucket: 'bracu-cart.firebasestorage.app',
    measurementId: 'G-QLJDJJEVH5',
  );
}
